/**
 * Created by enamul on 5/25/2017.
 */
console.log('server running...');


var fs = require('fs');
var http = require('http');

var express = require('express');
var app = express();
var bodyParser = require('body-parser');

// your express configuration here

var httpServer = http.createServer(app);

httpServer.listen(8082);


var myobj;

var data = {};



//}
/** bodyParser.urlencoded(options)
 * Parses the text as URL encoded data (which is how browsers tend to send form data from regular forms set to POST)
 * and exposes the resulting object (containing the keys and values) on req.body
 */
app.use(bodyParser.json({limit: '100mb'}));
app.use(bodyParser.urlencoded({limit: '100mb', extended: true}));



/**bodyParser.json(options)
 * Parses the text as JSON and exposes the resulting object on req.body.
 */
app.use(bodyParser.json());
// Add headers
app.use(function (req, res, next) {

  // Website you wish to allow to connect
  res.setHeader('Access-Control-Allow-Origin', '*');

  // Request methods you wish to allow
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');

  // Request headers you wish to allow
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

  // Set to true if you need the website to include cookies in the requests sent
  // to the API (e.g. in case you use sessions)
  res.setHeader('Access-Control-Allow-Credentials', true);

  // Pass to next layer of middleware
  next();
});


app.post("/saveRevision", function (req, res) {
// string generated by canvas.toDataURL()
  fs.writeFile('revisedFile.json',  JSON.stringify(req.body));
  console.log('saved in server');

});



  